apiVersion: v1
kind: Service
metadata:
    name: demo-api
    labels:
        app: demo-api
spec:
    selector:
        app: demo-api
    type: NodePort
    ports:
        - port: 3000
          targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: demo-api
spec:
    selector:
        matchLabels:
            app: demo-api
    replicas: 1
    template:
        metadata:
            name: demo-api
            labels:
                app: demo-api
        spec:
            containers:
                - image: copilot/demo-api
                  name: demo-api
                  imagePullPolicy: Always
                  env:
                      - name: SERVER_PORT
                        value: '3000'
                      - name: MONGO_HOST
                        value: 'mongo'
                      - name: MONGO_PORT
                        value: '27017'
                  resources:
                      requests:
                          memory: 200Mi
                          cpu: 500m
                      limits:
                          memory: 500Mi
                          cpu: '1'
                  ports:
                      - containerPort: 3000
                        name: api-port
                  readinessProbe:
                      httpGet:
                          path: /api
                          port: api-port
                      failureThreshold: 1
                      successThreshold: 1
                      initialDelaySeconds: 5
                      periodSeconds: 5
                      timeoutSeconds: 5
                  livenessProbe:
                      httpGet:
                          path: /api
                          port: api-port
                      failureThreshold: 3
                      successThreshold: 1
                      initialDelaySeconds: 10
                      periodSeconds: 30
                      timeoutSeconds: 5
